name: Build & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - name: Clean Node Modules
      run: rm -rf node_modules
    - run: npm ci
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: npm run build --workspace=packages/monadyssey-core
    - run: npm run build --workspace=packages/monadyssey-fetch
    - run: npm run test
