name: Build & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Clean Node Modules
      run: rm -rf node_modules
    - name: Install Dependencies
      run: npm install
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Build monadyssey-core
      run: npm run build --workspace=packages/monadyssey-core
    - name: Build monadyssey-fetch
      run: npm run build --workspace=packages/monadyssey-fetch
    - name: Run tests
      run: npm run test
